apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deploy
  labels:
    app: drupal
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal-cntr
          image: drupal:8
          ports:
            - containerPort: 80
