apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata: 
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-volume-claim
      containers:
        - name: postgres-cntr
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: drupal
            - name: POSTGRES_PASSWORD
              value: drupal
            - name: POSTGRES_DB
              value: drupal
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
