apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      protocol: TCP


